spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RecipeStore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      #file-size-threshold: 1MB
      #location: file:///C:/ServerRepo/RecipeStore/image/recipe/
      #imagesPath: /images/**
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

custom:
  path:
    images:
      location: file:///C:/ServerRepo/RecipeStore/image/recipe/
