spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/recipeWeb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      #file-size-threshold: 1MB
      #location: file:///C:/ServerRepo/RecipeStore/image/recipe/
      #imagesPath: /images/**
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

custom:
